name: CI Build

on:
  pull_request:
    branches:
      - main # O la rama principal de tu repositorio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # O la versión de Node.js que uses

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build
